library(shiny)
library(ggplot2)
library(dplyr)
library(tidyr)


data <- read.csv("camera_dataset.csv", stringsAsFactors = FALSE)
data <- separate(data, Model, into = c("Manufacturer", "Model"), sep = " ", extra = "merge")

ui <- fluidPage(
  # Feature 1: Camera Icon in the UI
  # An image of a camera icon is included in the Shiny app using the img tag. This feature serves as a visual element to enhance the overall design of the app, providing a recognizable and thematic representation related to the nature of the dataset. It adds a touch of aesthetics and reinforces the context of the application.
  img(src = "camera.jpg", height = 100, width = 150),
  titlePanel("1000 Cameras Data"),
  
  sidebarLayout(
    sidebarPanel(
      sliderInput("priceInput", "Price", min = min(data$Price), max = max(data$Price), value = c(100, 5000), pre = "$"),
      
      uiOutput("ManufacturerOutput"),
      
      sliderInput("yearInput", "Select Release Year", step = 1, min = min(data$Release.date), max = max(data$Release.date), value = c(min(data$Release.date), max(data$Release.date))),
      
      # Feature 2: Dynamic Result Text
      # Implemented a textOutput("resultText") in the UI to dynamically show the number of filtered camera options with a practical and engaging message. This feature enhances user understanding by providing immediate feedback on the number of relevant results, assisting users in quickly assessing the impact of their applied filters.
      textOutput("resultText"),
      
      # Feature 3: Download Button for Plot and csv
      # A download button ("Download Plot") is added to enable users to download the customized plot as a JPG file. This feature provides users with the ability to save and share the visual insights generated by the app, contributing to data dissemination and reporting.
      downloadButton("downloadPlot", "Download Plot"),
      downloadButton("downloadCSV", "Download CSV")
    ),
    
    mainPanel(
      plotOutput("coolplot"),
      br(), br(),
      DT::dataTableOutput("results")
    )
  )
)

server <- function(input, output) {
  
  output$ManufacturerOutput <- renderUI({
    selectInput("ManufacturerInput", "Select Manufacturer (Multiple Choices)", 
                choices = unique(data$Manufacturer), 
                multiple = TRUE,
                selected = "Canon")
  })
  
  filtered <- reactive({
    if (is.null(input$ManufacturerInput)) {
      return(NULL)
    }  
    
    data %>%
      filter(Price >= input$priceInput[1],
             Price <= input$priceInput[2],
             Manufacturer %in% input$ManufacturerInput,
             Release.date >= input$yearInput[1],
             Release.date <= input$yearInput[2]
      )
  })
  
  output$resultText <- renderText({
    if (!is.null(filtered())) {
      result_count <- nrow(filtered())
      if (result_count == 0) {
        "Oops! No cameras found. Try adjusting your filters."
      } else if (result_count == 1) {
        paste("Hooray! We found", result_count, "perfect match for you!")
      } else {
        paste("We found", result_count, "awesome options for you!")
      }
    } else {
      "No options found."
    }
  })
  
  output$coolplot <- renderPlot({
    if (is.null(filtered())) {
      return()
    }
    ggplot(filtered(), aes(Max.resolution, fill = Manufacturer)) +
      geom_histogram(color = "white", bins = 30, alpha = 0.7) +
      labs(title = "Distribution of Maximum Resolution",
           x = "Maximum Resolution",
           y = "Frequency",
           fill = "Manufacturer") +
      theme_minimal() +
      theme(legend.position = "top",
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            panel.background = element_blank(),
            axis.line = element_line(color = "black")) +
      scale_fill_brewer(palette = "Set3")
  })
  
  output$results <- DT::renderDataTable({
    filtered()
  })
  
  # Create a download handler for the plot
  output$downloadPlot <- downloadHandler(
    filename = function() {
      paste("plot_", Sys.Date(), ".jpg", sep = "")
    },
    content = function(file) {
      ggsave(file, plot = {
        ggplot(filtered(), aes(Max.resolution, fill = Manufacturer)) +
          geom_histogram(color = "white", bins = 30, alpha = 0.7) +
          labs(title = "Distribution of Maximum Resolution",
               x = "Maximum Resolution",
               y = "Frequency",
               fill = "Manufacturer") +
          theme_minimal() +
          scale_fill_brewer(palette = "Set3")
      }, device = "jpg", width = 8, height = 6, units = "in", dpi = 300)
    }
  )
  
  # Create a download handler
  output$downloadCSV <- downloadHandler(
    filename = function() {
      paste("camera_filtered_", Sys.Date(), ".csv", sep = "")
    },
    content = function(file) {
      write.csv(filtered(), file)
    }
  )
  
}

shinyApp(ui = ui, server = server)
